### PR TITLE
v0.13.1

### PR DESCRIPTION
**Pull request by dcposch**
I've started testing on Mac and Windows.

Create Torrent is broken again. Will fix before shipping.

### CODE REVIEW

**Comment by dcposch** [comment]
### Testing
- [ ] Create Torrent page
  - [ ] Single file
  - [ ] Multi file
  - [ ] Ways to get there: drag folder, Ctrl+N, click the + button in the torrent list
  - [ ] Comment and private flag. Use `parse-torrent`, check that the fields are right
- [ ] Preferences
  - [ ] Set a different download folder
  - [ ] Start a torrent. Delete the folder. Restart the app. Note "missing path" warning.
  - [ ] Set a different fallback player. Play something the video tag doesn't support
  - [ ] Set always use external player. Play something the video tag *does* support.
- [ ] Playback
  - [ ] Video. Try all the player controls.
  - [ ] Drag and drop soft subs
  - [ ] Audio
- [ ] Casting
  - [ ] DLNA
  - [ ] AppleTV
  - [ ] Chromecast

**Comment by dcposch** [comment]
K, everything works now, as far as I can tell.

**It would be awesome if someone could test on Linux.** Maybe @grunjol ?

Planning to release tonight

**Comment by dcposch** [comment]
@feross merging since this is already on `npm`. I'll wait until later to update the website and auto updaters in case someone wants to test Linux first.

**Comment by grunjol** [comment]
tested in linux, working fine

**Comment by feross** [comment]
@grunjol Good point. Will fix.

**Comment by feross** [comment]
@grunjol PR here: https://github.com/feross/webtorrent-desktop/pull/922

**Pull request merged**
