### PR TITLE
Create Torrent page

### PR DESCRIPTION
**Pull request by dcposch**
Done:
* Handle drag-and-drop (gives you an array of W3C File objects) and the Create Torrent menu item (gives you a path to a folder)
* Show the user which torrent they're about to create

Left to do:
- [x] Change from modal to page
- [x] Add options.
  - We can't have a name option, for now. WebTorrent requires that to be the name of the file or folder we're seeding from
  - [x] We should have an option to change the announce list
  - [x] Private bit
  - [x] Comment
  - Order of files (not doing this for now -- doesn't seem important and it's a decent amount of work, doing it right would require a drag-drop ordered list control)

### CODE REVIEW

**Comment by feross** [comment]
Fixes #389

**Comment by dcposch** [comment]
### New look

** Basic **

image

** Advanced **

image

**Comment by dcposch** [comment]
I think this is ready to go now.

**Caveats**
* The comment field doesn't work yet. See https://github.com/feross/create-torrent/issues/36
* You can add and remove trackers, but removing the built-in WebTorrent trackers (the ones that start with `wss://`) doesn't work. They get re-added automatically by `create-torrent` because we set the `WEBTORRENT_ANNOUNCE` global variable. However, we can't just remove that variable because we want `webtorrent` to use those trackers for existing torrents.
  I'm thinking we should add a different mechanism to tell `webtorrent` which trackers to always use. Global variables are gross anyway.

**Comment by dcposch** [comment]
@feross might want to review

**Comment by grunjol** [comment]
Nice work on this. My only suggestion (and i am not a designer) is about the style. I faced the same problem when i was doing the settings page (PR #426). 
There is no definition on styling in the app (except for the gorgeous torrent list and player).
I saw you started using some kind of 'material design' but with a light theme, when the app clearly use a dark one. Now i see you go with the dark theme approach but i found the palette kind of high contrast B/W.

What we need to define:

* We go with the 'Material Design' style 
* An 'Atom-alike' one (like you can see in the screenshots of https://github.com/feross/webtorrent-desktop/pull/426)
* A new one, combining styles

If we go with the material design we need to follow it. A couple of days ago google released an example of material design for desktop, using the [Chrome Browser as an example](http://www.theverge.com/2016/4/23/11495442/chrome-os-material-design-update-rolling-out-screenshots). 

To be clear,it is not my intention to hijack your PR, nor criticizes your great work, just an attempt to define this thing to allow more people to get involved.

**Comment by dcposch** [comment]
@grunjol I agree. We have a lot of colors, margins, font sizes, and so on that could be cleaned up and made consistent across the app.

* I think it would be sweet to get a review from a designer. They could tell us what specifically needs to be fixed.
* Then, we could go in and try to refactor and simplify `index.css`

I think we can do that in a future PR tho

**Comment by feross** [comment]
👍

**Pull request merged**
