### PR TITLE
Save video position

### LINKED ISSUE #405: Remember video position
Would be great if playing video and pressing the back button, then playing the video would resume at the last position instead of starting the video from the start.

### PR DESCRIPTION
**Pull request by dcposch**
Fixes #405 

Also cleaned up the styling on the list of files when you expand a torrent

### CODE REVIEW

**Comment by dcposch** [comment]
screen shot 2016-05-21 at 8 15 41 am

**Comment by feross** [comment]
Nice, this looks really good! Especially the changes to the file list. Looks really pro.

The only thing I ran into is that automatic subtitle detection throws an exception and that prevents playback.

The default state object only contains `length` and `name` properties for each file, so it's relying on the 'metadata' event to populate the `path` property which is used here (https://github.com/feross/webtorrent-desktop/blob/ba41ce5f9a0404290766d35c19511ba07861cd24/renderer/index.js#L722).

This change (https://github.com/feross/webtorrent-desktop/pull/554/commits/ba41ce5f9a0404290766d35c19511ba07861cd24) prevents the 'metadata' event from updating `torrentSummary.files` for the default torrents, so they'll always lack a `path` property.

Once that's fixed up, and you rebase, this is good to merge. :

**Comment by dcposch** [comment]
> This change (ba41ce5) prevents the 'metadata' event from updating torrentSummary.files for the default torrents, so they'll always lack a path property.

Good call! Fixing

**Comment by dcposch** [comment]
> The only thing I ran into is that automatic subtitle detection throws an exception and that prevents playback

That's probably already on master, right, since this PR doesn't change subtitle behavior?

Was it `language-detect`, `srt-to-vtt`, or something else that threw the exception?

**Comment by feross** [comment]
> That's probably already on master, right, since this PR doesn't change subtitle behavior?

The exception is caused by this PR, since the `path` property is not set on the files in `torrentSummary.files` anymore. The source of the bug is the 'metadata' event, but it doesn't manifest itself until the subtitles code runs because it tries to access `torrentSummary.files[0].path`.

**Pull request merged**
