### PR TITLE
Sketch: Remove torrent/data modal

### PR DESCRIPTION
**Pull request by mathiasvr**
I think an option to remove all data, as requested in #560, is a good idea, so I made a simple modal for choosing this, like @demoneaux suggested.

skaermbillede 2016-06-01 kl 16 23 58

Maybe this should just be an option in the right-click menu or preferences, but it might be nice for new users to have the choice at first? A cancel button could also be added?

Thoughts?

### CODE REVIEW

**Comment by feross** [comment]
@mathiasvr Thanks for taking the initiative and sending this PR!

I think this should be an item in the right-click menu. I think the average user will be confused by an option like this -- "what's the difference between deleting the torrent vs. deleting all the data?" 

I wrote a comment with my thoughts here: https://github.com/feross/webtorrent-desktop/issues/560#issuecomment-223854963

**Comment by mathiasvr** [comment]
@feross I think you are right about these options being confusing. I read your comments on the issue and updated the PR so that the modal now looks like this:
skaermbillede 2016-06-13 kl 15 40 19
I prepared a `keepFiles` modal property so the modal can be used for deleting data as well.

I went for a simple message but we could add more info like Transmission does?

**Comment by mathiasvr** [comment]
Just rebased everything on top of master and squashed the commits. I have integrated the modal with the remove data feature from #641.

**Comment by dcposch** [comment]
Looks great to me. I'll rebase it again and merge.

**Pull request closed without merging**
