### PR TITLE
Better subtitles support

### PR DESCRIPTION
**Pull request by dcposch**
- [x] Simplify. Remove redundant `state.playing.subtitles.enabled`. Remove hacks like regex-parsing the 'label' of each subtitle, using the label as the identifier, etc
- [x] Detect subtitles next a video file automatically
- [x] Default to the user's language instead of just the first subtitle track

### CODE REVIEW

**Comment by dcposch** [comment]
image

**Comment by grunjol** [comment]
I just tested your code, and the only problem I am getting is when adding multiples subtitles manually. 

* Add First subtitle. Subtitle is added and starts playing.
* Add second subtitle. Subtitle is added and starts playing.
* Add third subtitle. Subtitle is added but second subtitle keeps playing.

**Comment by grunjol** [comment]
Oops, you already merge it. I will open an issue.

**Comment by dcposch** [comment]
@grunjol yeah, right now it replaces the currently-playing subtitle only if it's in the OS language

**Comment by dcposch** [comment]
see https://github.com/feross/webtorrent-desktop/blob/master/renderer/index.js#L639

that means you can drop a folder full of subtitles and it will pick the "right" one (eg if your computer is set to Spanish, it'll pick the Spanish subtitle track)

maybe we want a different behavior

**Comment by grunjol** [comment]
My machine is in English.

I added the subs manually in this order, each one individually

First test
* Start playing video
* Add Portuguese => PT plays
* Add French => FR plays
* Add German => FR keeps playing

Second test
* Start playing video
* Add French => FR plays
* Add German => DE plays
* Add Portuguese => DE keeps playing

I dont know why the second is added and displayed buy not the third, and no matter the order the second is picked if no matching languages.

I agree with you, If you add a lot of subtitles you need to select which one to show, and its fine to try to select the OS-matching one. But if you add a new one, I expect that one to be selected regardless the OS language you are running.

**Comment by feross** [comment]
> But if you add a new one, I expect that one to be selected regardless the OS language you are running.

Agree that this is the right behavior.

**Comment by dcposch** [comment]
Already done in #529

**Comment by dcposch** [comment]
@grunjol i couldn't reproduce what you described with the second subtitle you added

**Comment by feross** [comment]
@dcposch See https://github.com/feross/webtorrent-desktop/issues/534 -- it might need to be closed if it's already fixed

**Pull request merged**
