### PR TITLE
Add volume controls

### PR DESCRIPTION
**Pull request by grunjol**
i am not a great designer but i think its not too ugly... and it works
volume-control

### CODE REVIEW

**Comment by grunjol** [comment]
feedback is always welcome

**Comment by grunjol** [comment]
Change to circle to be consistent with the position handler

image

**Comment by gdelavald** [comment]
@grunjol Awesome work!
A few suggestions:
- Dragging the volume control actually drags the whole window, this feels counter intuitive and might hurt UX.
- Also it only changes when you click exactly on the volume bar, I think it would be better to increase the 'hitbox'.

**Comment by grunjol** [comment]
* That's weird, I am not getting any windows dragging in any moment on volume slider, bar, or icon... is it happening to anyone else?
* You are right, the hit area is narrow, i agree with you, i think its related to the use of input[type=range], a pure graphical slider should fix that.

Also, you can control volume dragging the circle, clicking in the bar (narrow as you said) or using the wheel.

**Pull request merged**
