### PR TITLE
Added the option to activate or deactivate sound notifications

### PR DESCRIPTION
**Pull request by kaotisk-hund**
I figured out how to make the option go in preferences menu but I can't find where I have to edit so the sound notifications go on/off. Any help?

### CODE REVIEW

**Comment by kaotisk-hund** [comment]
travis-ci says "state is not defined" but it runs ok and I got no error while running it. Any ideas on how to approach this better?

**Comment by kaotisk-hund** [comment]
Now the checks are passing but it doesn't work...

**Comment by kaotisk-hund** [comment]
How to gain access to saved configuration of webtorrent-desktop into lib/sound.js?

**Comment by mathiasvr** [comment]
You could create an init function as in [lib/cast.js](https://github.com/feross/webtorrent-desktop/blob/4bb2056bc9c1a421815b97d03ffed512575dfde0/src/renderer/lib/cast.js#L33) to store the app state.

**Comment by feross** [comment]
Thanks for the PR, but I don't want a preference for every trivial option that a user could want. I think we should just do the right thing, which is probably to remove the sounds entirely it seems.

**Pull request closed without merging**
