### PR TITLE
Minimize to tray

### PR DESCRIPTION
**Pull request by dcposch**
image

### CODE REVIEW

**Comment by dcposch** [comment]
- [x] Test on Linux
- [ ] Test on Windows
- [ ] Test on Mac

@feross

**Comment by dcposch** [comment]
Mac should be totally unaffected. No tray icon there.

**Comment by feross** [comment]
Looks good on Mac!

**Comment by c0b41** [comment]
@dcposch Not working, any idea?
ekran goruntusu - 2016-03-29 20 14 41

**Comment by dcposch** [comment]
Standard Ubuntu w Unity, or are you running a different window manager?

**Comment by c0b41** [comment]
@dcposch 

actualy already installed ***libappindicator1***  but not working.. anyway

ekran goruntusu - 2016-03-30 00 52 34

**Comment by dcposch** [comment]
Looks like you're running this? https://elementary.io/

Sorry man, I have no idea. Desktop Linux is fragmented enough that it's impossible to test on all of them.

I want to make sure it works on a vanilla Ubuntu setup, both LTS and stable.

**Comment by dcposch** [comment]
We will add a prefs window, though, so that you can at least disable "minimize to tray". Currently, you probably can't quit WebTorrent at all short of using `kill` or rebooting (because click X only hides the window, and Tray Icon > Quit isn't working for you).

**Comment by c0b41** [comment]
@dcposch yeah same problem :+1:

**Comment by feross** [comment]
@c0b41 What is the way that this fails for you?

Do you see no tray icon at all, but WebTorrent is still running after you click `X`?

Or is the tray icon showing up, but you can't select any of the commands?

**Comment by feross** [comment]
I opened a new issue to track this: https://github.com/feross/webtorrent-desktop/issues/303

**Comment by c0b41** [comment]
@feross not seen tray icon, stil runnig webtorrent. thanks for this issue :+1:

**Pull request merged**
