### PR TITLE
Linux .deb file: update symlink on package update

### LINKED ISSUE #326: Ubuntu "package is of bad quality"
```
Lintian check results for /home/dc/Downloads/webtorrent-desktop_0.3.1-1_amd64.deb:
E: webtorrent-desktop: control-file-has-bad-permissions postinst 1363 != 0755
E: webtorrent-desktop: control-file-has-bad-permissions postrm 1363 != 0755
```

image

### PR DESCRIPTION
**Pull request by grunjol**
Fixes #326 

this set correct mode in pre and post install scripts and updates symlink on package update

### CODE REVIEW

**Comment by grunjol** [comment]
@dcposch tested in debian 8 and ubuntu 15.10, could you test it too?, just to be sure to merge it

**Comment by grunjol** [comment]
included nobin-debian-installer 0.0.7 which is also in #328

**Comment by dcposch** [comment]
Checked out  the branch and ran `npm install && npm run package -- linux`

Getting the following error. Missing `package.json` entry?

```
Error: Cannot find module 'bl'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/dc/webtorrent-desktop/node_modules/nobin-debian-installer/node_modules/tar-stream/extract.js:2:10)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/dc/webtorrent-desktop/node_modules/nobin-debian-installer/node_modules/tar-stream/index.js:1:81)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```

**Comment by grunjol** [comment]
`nobin-debian-package` does not use `bl` . 
`tar-stream` use it and its declared in package.json

I removed node_modules and tun install and package on that branch and its working fine....

**Comment by grunjol** [comment]
It seems the dependency is missing in your project

**Comment by dcposch** [comment]
Yeah I deleted `node_modules` completely and reinstalled, and now it works. NPM is surprisingly fragile.

It still says the package will take "120 GB on disk", which I think is 1000x the real value :)

**Comment by dcposch** [comment]
It also says "no screenshot available" -- in case it's quick and easy I'd add one. Regardless of that, once it says 120MB instead of 120GB, feel free to merge!

I recommend using the squash & rebase button instead of the merge commit button

**Comment by dcposch** [comment]
Actually, one more bit of borkage.

After installing successfully, here's what happens when I try to uninstall:

```
dc@freya:~$ sudo apt-get purge webtorrent-desktop 
[sudo] password for dc: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-4.2.0-27 linux-headers-4.2.0-27-generic
  linux-image-4.2.0-27-generic linux-image-extra-4.2.0-27-generic
Use 'apt-get autoremove' to remove them.
The following packages will be REMOVED:
  webtorrent-desktop*
0 upgraded, 0 newly installed, 1 to remove and 74 not upgraded.
After this operation, 120 GB disk space will be freed.
Do you want to continue? [Y/n] Y
dpkg: unrecoverable fatal error, aborting:
 files list file for package 'webtorrent-desktop' contains empty filename
E: Sub-process /usr/bin/dpkg returned an error code (2)
```

**Comment by grunjol** [comment]
good catch! i am checking the size and empty filename erro problems

**Comment by grunjol** [comment]
@dcposch to fix the package list go and edit package list file
`sudo gedit /var/lib/dpkg/info/webtorrent-desktop.list `
make sure the first line is 
`/.`
and not
`/`

**Comment by feross** [comment]
@dcposch Can you confirm this is working for you now? If so, we can include a working .deb in the next release!

**Comment by feross** [comment]
@grunjol Nice work getting this all figured out!

**Comment by grunjol** [comment]
Installation & Purge working fine
```
sudo dpkg -i dist/webtorrent-desktop_0.3.1-1_amd64.deb 
Selecting previously unselected package webtorrent-desktop.
(Reading database ... 1330923 files and directories currently installed.)
Preparing to unpack .../webtorrent-desktop_0.3.1-1_amd64.deb ...
Unpacking webtorrent-desktop (0.3.1-1) ...
Setting up webtorrent-desktop (0.3.1-1) ...
grunjol@here:~/workspaces/wt/webtorrent-desktop$ 
```

```
sudo apt-get purge webtorrent-desktop 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  webtorrent-desktop*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 118 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 1331000 files and directories currently installed.)
Removing webtorrent-desktop (0.3.1-1) ...
grunjol@here:~/workspaces/wt/webtorrent-desktop$ 
```

**Comment by feross** [comment]
@grunjol I'm curious if this will work from my machine (OS X), which I use for the releases. I will do a test build from my machine (OS X) and send you a .deb to test. Is that cool?

**Comment by grunjol** [comment]
@feross sure

**Comment by feross** [comment]
@grunjol Here's the link: https://instant.io/#91686440f335771221ef7d19dc6b7e63c901602a

**Comment by grunjol** [comment]
Installation
```
sudo dpkg -i ~/Downloads/webtorrent-desktop_0.3.1-1_amd64.deb 
Selecting previously unselected package webtorrent-desktop.
(Reading database ... 1330923 files and directories currently installed.)
Preparing to unpack .../webtorrent-desktop_0.3.1-1_amd64.deb ...
Unpacking webtorrent-desktop (0.3.1-1) ...
Setting up webtorrent-desktop (0.3.1-1) ...
```

RUN!
```
grunjol@here:~$ webtorrent-desktop 
crash reporter started
init: 941.227ms
...
```
Remove
```
sudo apt-get purge webtorrent-desktop 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  webtorrent-desktop*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 118 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 1331000 files and directories currently installed.)
Removing webtorrent-desktop (0.3.1-1) ...
```

**Comment by feross** [comment]
LGTM!

**Comment by dcposch** [comment]
@grunjol the new deb files works great! Shows 117MB instead of 120GB now, also great

One small warning on uninstall:

```
$ sudo apt-get purge webtorrent-desktop 
[sudo] password for dc: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-4.2.0-27 linux-headers-4.2.0-27-generic linux-image-4.2.0-27-generic linux-image-extra-4.2.0-27-generic
Use 'apt-get autoremove' to remove them.
The following packages will be REMOVED:
  webtorrent-desktop*
0 upgraded, 0 newly installed, 1 to remove and 74 not upgraded.
After this operation, 118 MB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 297982 files and directories currently installed.)
Removing webtorrent-desktop (0.3.2-1) ...
dpkg: warning: while removing webtorrent-desktop, directory '/opt/webtorrent-desktop/resources' not empty so not removed
```

Checking what's in that folder:
```
$ ls /opt/webtorrent-desktop/resources/ -lha
total 172K
drwxr-xr-x 2 root root 4.0K Apr  7 01:33 .
drwxr-xr-x 3 root root 4.0K Apr  7 01:33 ..
-rw-r--r-- 1 root root 163K Apr  6 19:02 atom.asar
```

**Comment by feross** [comment]
This may have something to do with Electron renaming atom.asar to electron.asar in the most recent version.

@dcposch Perhaps this was left over from a previous install?

**Comment by dcposch** [comment]
yes that's probably it.

**Comment by dcposch** [comment]
Tried again. Works beautifully. Thanks @grunjol !

**Pull request merged**
