### PR TITLE
Play unsupported files in VLC

### PR DESCRIPTION
**Pull request by dcposch**
**With VLC present**
image

**Without VLC**
image

### CODE REVIEW

**Comment by dcposch** [comment]
image

**Comment by dcposch** [comment]
**Work left to do**
* Make the cross platform VLC detection from `webtorrent-cli` into its own module
* Use it to support windows

Right now Play in VLC only works on Linux, specifically it expects `vlc` to be on your path.

**Comment by dcposch** [comment]
We should test this on Windows 7, 10, OSX and Ubuntu before merging.

In each case we should:
* Start WebTorrent with VLC **not installed**
* Click the "Install VLC" button. It should take you to the VLC website
* The button should now say "Play in VLC". Click it again. You get an error saying it couldn't find VLC.
* Install VLC
* Click "Play in VLC" again. It should work this time.

If that works on those four OSs then I think we're good to go.

**Comment by dcposch** [comment]
@feross runs on Mac an Linux now.

I borrowed the VLC detection from `webtorrent-cli`. Cross platform detecting and running VLC now happens in `vlc.js`, which I can make into its own module later.

**We shoul test that it works on Windows before merging.**

**Comment by feross** [comment]
https://npmjs.com/package/vlc-command

**Comment by dcposch** [comment]
@feross nice. I have to get in the habit of making small modules. Yours looks v clean.

Tested & Play in VLC works on Windows now.

**Comment by dcposch** [comment]
Also fixed in Windows.

Works in Mac and Windows. It worked on Linux before and probably still does -- let me know if you run into issues! Especially @grunjol who's using something different from Ubuntu.

Time to 🚢 🚢 🚢

**Comment by grunjol** [comment]
Tested and working in Debian 7

**Comment by feross** [comment]
👍 👍

**Comment by luisrudge** [comment]
I have VLC installed, but webtorrent is asking me to install VLC:

image

image

I'm using Windows 10.

**Comment by feross** [comment]
@luisrudge I suggest checking that you're using the latest version of WebTorrent (See the 'About WebTorrent' menu). You should see version 0.9.0.

If you're using the latest version and still see this issue, then please open a new issue.

**Pull request merged**
