### PR TITLE
Use raised button for inline button

### PR DESCRIPTION
**Pull request by feross**
Before:

screen shot 2016-09-13 at 8 16 20 am

After:

screen shot 2016-09-13 at 8 16 13 am

### CODE REVIEW

**Comment by mathiasvr** [comment]
LGTM, but I think the `Cancel` and `Create Torrent` should have the same style, either raised or flat.

**Comment by dcposch** [comment]
Needs more vertical space imo

**Comment by feross** [comment]
@mathiasvr I didn't change the `Cancel` button style. That's just an artifact of where my mouse was when I took the screenshot ;)

**Comment by feross** [comment]
@dcposch You're right, let's do in future PR

**Pull request merged**
