### PR TITLE
Add subtitle support (via drag-n-drop)

### PR DESCRIPTION
**Pull request by feross**
Drag and drop a subtitles file (.srt or .vtt) onto the player (or the
app icon on OS X) to add subtitles to the currently playing video.

For #281

With controls hidden:

screen shot 2016-04-08 at 01 29 26

With controls shown:

screen shot 2016-04-08 at 01 36 52

Modeled the text style after VLC. White text, black outline, gray shadow to the bottom right.

### CODE REVIEW

**Comment by MoOx** [comment]
Wow, that was fast!

**Comment by feross** [comment]
@MoOx thanks!

**Comment by grunjol** [comment]
is srt-to-vtt really needed?

AFAIK <video> tag has native srt support, i mean, vtt is kinda a superset of srt.

Let me check but i am pretty sure its fully compatible with <track> tag

**Comment by grunjol** [comment]
@feross modified subtitle state structure to handle multiple tracks, will be working on it a little bit more

Do we have a _tooltip like_ menu we can display on CC icon selection to display and select subtitles when more than one is available?

**Comment by grunjol** [comment]
webtorrent no cc
webtorrent open sub
webtorrent cc enabled

**Pull request merged**
