### PR TITLE
Remove global shortcuts when player isn't active

### PR DESCRIPTION
**Pull request by dcposch**
@feross

### CODE REVIEW

**Comment by dcposch** [comment]
Fixes #263

**Comment by dcposch** [comment]
Merged. I just forgot to force push `dc/shortcuts` first

**Comment by ungoldman** [comment]
:scream: force push? :scream:

**Comment by dcposch** [comment]
You never want to force push master, but its cool to rebase and force push
feature branches before they're merged

That lets you keep a nice linear history w/out merge commits

**Comment by ungoldman** [comment]
@dcposch yep I do that with feature branches too, was worried it was master. ignore me, please carry on!

**Pull request closed without merging**
