### PR TITLE
WIP: auto download subtitles from providers like opensubtitles

### PR DESCRIPTION
**Pull request by Diogo-Ferreira**
This PR adds the possibility to download subtitles automatically from providers like opensubtitles.org. 

I wanted to add this feature because I liked [Kodi  subtitle auto download feature](http://cdn.htpcbeginner.com/images/2015/10/06-Add-Kodi-Subtitles-list.jpg) and found it very useful.

Currently the user can click on ["auto download"](http://diogoferreira.ch/webtorrent/webtorrent_desktop_auto_download.png) and the code will download the 3 most popular subs based on the current playing file. The subs are stored in the same folder as the playing file, prefixed with "auto_downloaded". Every time a sub is downloaded, the controller add's it in the player.

If no subs are found, an error message is displayed, and for now the only provider implemented is opensubtitles.

The next steps would be to :
- create an ui or dialog to allow the user to choose which subs he wants to download
- when no subs are found, allow the user to enter other information as the imdbid for instance.
- get user main language or allow him to choose it

What to you think about this feature ?

This is my first open source contribution so don't hesitate to tell me if I'm doing something wrong, I will appreciate it and improve myself  :).

### CODE REVIEW

**Comment by balta2ar** [comment]
I miss this feature a lot.

**Comment by codealchemist** [comment]
Hi @Diogo-Ferreira!
I added this feature on #677.
But the legality for this feature is not very clear and the team decided to stay legal, which I believe is the best way to move on (remember PopcornTime?).

My advice is to put effort in a plugin system, which will enable us to add this feature as an external plugin, which would be awesome ;)

I'm also looking forward to work on a plugin system soon.
Thanks for contributing! :)

**Comment by codealchemist** [comment]
I'll close this PR because of the same conclusion on #677.
And again, I really like this idea and would love to see it implemented as a plugin.
Cheers!

**Comment by codealchemist** [comment]
I'll close this PR because of the same conclusion on #677.
And again, I really like this idea and would love to see it implemented as a plugin.
Cheers!

**Comment by Diogo-Ferreira** [comment]
Hi @codealchemist ,
I understand the problem, thank you for your time anyway.

I think too that a plugin system would be awesome, I look forward to seeing it, and to contribute to it if I can help :)

Cheers.

**Pull request closed without merging**
