### PR TITLE
Add 'Segoe UI'

### PR DESCRIPTION
**Pull request by avamsi**
Almost every other app in Windows uses 'Segoe UI' and it'd be nice if WebTorrent Desktop uses the same.

### CODE REVIEW

**Comment by feross** [comment]
Nice, makes a big difference!

**Comment by feross** [comment]
Before:

screen shot 2016-08-23 at 2 51 48 am

After:

screen shot 2016-08-23 at 2 51 35 am

**Comment by feross** [comment]
The only change I'm going to make to this PR is to put the 'Segoe UI' font in an `.app.is-win32` CSS selector so some poor designer who owns a Mac and has 'Segoe UI' installed doesn't somehow end up with the UI using that font. Because I'm not sure if the 'BlinkMacSystemFont' works on prior versions of OS X.

**Comment by feross** [comment]
Fixed here: https://github.com/feross/webtorrent-desktop/commit/9ad0316dffe9ac189a310f4a42d0dd89fbd14259

**Comment by avamsi** [comment]
Thanks for the fix and quick approval!

**Comment by feross** [comment]
Will be part of the next release, probably v0.13.0 or v1.0

**Pull request merged**
