### PR TITLE
Auto download subtitles

### PR DESCRIPTION
**Pull request by codealchemist**
Added subtitles autoloading.
Uses OpenSubtitles API.
All available subtitles for configured language are downloaded into the _subs_ folder on the torrent path.
Then, one after one they are loaded into WebTorrent.
It's a _brute force_ approach to subtitle loading.

**TODO:** add subtitles preferences with language selector and total amount of downloaded subtitles limit.

### CODE REVIEW

**Comment by codealchemist** [comment]
Another todo: avoid re-downloading existing subs.

**Comment by codealchemist** [comment]
I've found issues with single video files.
Fixing that.

**Comment by codealchemist** [comment]
Another TODO: add app notifications for errors.

**Comment by mathiasvr** [comment]
I also thought about adding a subtitle downloader, but I think it would make more sense as a `plugin` in relation to #664. However if many people is interested in this I guess it would make sense to include it by default.

Also I edited the title, since I initially thought this was about loading embedded subtitles (like in mkv files).

**Comment by codealchemist** [comment]
Thanks for the title adjustments @mathiasvr!
If we can create a plugin repository for WebTorrent that would be **awesome**. 
I'm thinking about something like Sublime Text's _Package Control_, which is integrated into the app.
I'd like to help with the subtitles downloader either way.
Whatever the community and the project maintainers prefer.

**Comment by dcposch** [comment]
i don't like hitting a central server every time a file is opened. not ideal for privacy or performance.

what about checking OpenSubtitles only after the user clicks the CC button?

currently, that pops open an Open File dialog

we could make it show a menu instead: Open Subtitles File, Search OpenSubtitles. If the user clicks that second option, it would show a loading spinner, then a list of available languages. they can select one to download and use that subtitle track.

--

to be honest, i'm not sure we need this. i don't know any video player that has this feature. even VLC supports it only via a third-party plugin called VLsub.

**Comment by codealchemist** [comment]
@dcposch, the latest code on the PR allows *enabling / disabling* automatic subtitles downloading from *preferences*.
I still think we should not download already downloaded subtitles, that's not terrible but it's not good enough.

But in general it's a cool and useful feature that might be appreciated by anyone who uses subtitles.
It makes it *tremendously easy* to get subtitles, even easier than with VLSub where you need to make several clicks and write stuff manually to identify the video file _(we can't just use hashes when streaming since the file isn't downloaded yet and can't be hashed)_.

That being said, I really like the idea of having a plugin repository integrated in the app.
And I'm looking forward to help with that if I can and if that's something wanted.
:)

**Comment by feross** [comment]
Thanks for the PR, but we're not going to add this feature to WebTorrent Desktop, because the legality of OpenSubtitles is not clear to us.

Once there's a plugin system, I suppose you could build this as a plugin. But it's not something the WebTorrent team can endorse.

**Comment by codealchemist** [comment]
I see. Thanks for the explanation @feross!
:)

**Comment by feross** [comment]
Sure thing. 👍

**Comment by janat08** [comment]
There're some other players that use this that are open source, likely even copyleft. I don't know which one I use that has it. Perhaps ask them about it.

**Comment by janat08** [comment]
SMPlayer has it and is GNU.

**Comment by janat08** [comment]
I say if you let user decide what and if he wants the subtitles choosing "find subtitles" option, then it becomes his responsibility what happens right?

**Pull request closed without merging**
