### PR TITLE
Package 32bits and 64bits linux versions in zip and deb formats

### PR DESCRIPTION
**Pull request by grunjol**
This PR complements #335 and finishes #369

### CODE REVIEW

**Comment by feross** [comment]
LGTM

**Comment by feross** [comment]
What is libc6 needed for?

**Comment by grunjol** [comment]
libc6 is the standard C library. electron packages all the libraries but assumes you have libc6 in your system (debian depends on that library, so its always dependant)

**Comment by feross** [comment]
Sounds good.

**Pull request merged**
