### PR TITLE
Allow dragging magnet links (Fix #284)

### LINKED ISSUE #284: Allow dragging magnet links
It would be handy to have the app accept dragging of torrent links instead of doing a manual copy-paste.

### PR DESCRIPTION
**Pull request by feross**

### CODE REVIEW

**Comment by mathiasvr** [comment]
Works well for me, but we might want to handle incompatible text at some point.

**Comment by codealchemist** [comment]
You were ahead of me by 10hs on this one @feross xD
Works ok, thanks!

**Comment by feross** [comment]
@mathiasvr handle incompatible text? Do you mean show a friendlier message instead of `ENOENT: no such file or directory`? Open a new issue?

**Comment by mathiasvr** [comment]
@feross yes exactly, I think errors displayed in the UI should be short and descriptive, but I don't think it's an important issue right now.

**Pull request merged**
