### PR TITLE
Remove weird outline from “Create Torrent” button.

### LINKED ISSUE #989: Create Torrent button has odd outline
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

0.17.0

**What operating system and version?**

Mac

**What did you do?**

Drop file on app, which loads Create Torrent page.

**What did you expect to happen?**

Submit button should look normal.

**What actually happened?**

It has an odd outline. See pic:

screen shot 2016-09-29 at 11 53 37 am

I thought that this was just an artifact of the integration testing, but it's actually the way the button looks. Let's fix it.

### PR DESCRIPTION
**Pull request by demoneaux**
The outline was caused by the wrong class being applied to the button.

Closes #989.

### CODE REVIEW

**Comment by demoneaux** [comment]
@feross do you think it's a good idea to prefix the class names of pages with something like `page-`? eg. `page-create-torrent`, `page-preferences`, etc. to provide a distinction?

**Comment by dcposch** [comment]
This is my bad. The problem is that the `create-torrent` CSS class is used twice, once on the outer div for the whole Create Torrent page and again on the Create button.

There are some CSS rules meant for the whole page that are mistakenly applying to the button.

I would change the button class to `create-torrent-button` and modify the integration test accordingly.

**Comment by demoneaux** [comment]
@dcposch updated!

**Comment by dcposch** [comment]
How do you mark "requested changes" as done?

Github has complexified itself :(

**Comment by demoneaux** [comment]
Yeah, not too sure. Maybe @feross can change his review or something?

**Comment by feross** [comment]
Oh, I think if I "request changes" then I'm blocking the merge until I approve. I'll use "comment" instead of "request changes" in the future 👍

**Comment by feross** [comment]
@demoneaux I like your idea of prefixing page classes with 'page-' to distinguish them.

**Pull request merged**
